config/routes.rb
EComm::Application.routes.draw do
  
  resources :specialoffers
  get "specialoffers/index"

  resources :specials

  get "pages/home"

  get "pages/contact"

  get 'admin' => "admin#index"

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end

  resources :users

  get "payment_notification/create"

  resources :orders

  resources :line_items

  resources :carts

  get "store/index"

  resources :products
  
  resources :payment_notifications
  

  
  root :to => 'store#index', :as => 'store'

end

app/models/product.rb
class Product < ActiveRecord::Base
  
  has_many :line_items
  before_destroy :ensure_not_referencing_by_any_line_item
  
  validates :title, :description, :presence => true
 # validates :image_url, :allow_blank => true, :format => {:with => %r{\.(gif|jpg|png)$}i,:message => 'must me a URL for GIF,JPG or PNG image.'}
  validates :price, :numericality => {:greater_than_or_equal_to => 0.01 } 
  validates :title, :uniqueness => true 
  
  has_attached_file :photo,
                    :url  => "/assets/products/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/products/:id/:style/:basename.:extension"

  validates_attachment_presence :photo
  validates_attachment_size :photo, :less_than => 5.megabytes
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']
  
   PRODUCT_TYPES = ["Normal","Special"]
 
 private 
 
 #ensure that there is no line items referencing this product.
 
 def ensure_not_referencing_by_any_line_item
   if line_items.empty?
     return true
   else
     errors.add(:base,'Line Items presents')
     return false
   end
 end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  
  skip_before_filter :authorize, :only => [:show]
  
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, :notice => 'Product was successfully created.' }
        format.json { render :json => @product, :status => :created, :location => @product }
      else
        format.html { render :action => "new" }
        format.json { render :json => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, :notice => 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for @product, :html => { :multipart => true } do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description,:cols => 40,:rows => 3 %>
  </div>
  
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div>
     <%= f.label :photo, "Photo"%> <br />
	 <%= f.file_field :photo %>
  </div>
  
  <div class="field">
      <%= f.label :type %><br />
      <%= f.select :type1, Product::PRODUCT_TYPES, :prompt => 'Select a type' %>
  </div>
  <div class="field">
      <%= f.label :oldprice %><br />
      <%= f.text_field :oldvalue %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>

<% @products.each do |product| %>
  <tr class="<%= cycle('list_line_odd','list_line_even') %>">
	<td>
	<%= image_tag(product.image_url,:size => "110x110") %>
	</td>
    
    <td class="list_description">
	    <dl>
        	<dt><%= product.title %></dt>
			<dd><%= strip_tags(product.description)%></dd>
    	</dl>
    </td>
		<td class="list_action">
		<%= link_to 'Show', product %></br>
		<%= link_to 'Edit', edit_product_path(product) %></br>
    	<%= link_to 'Destroy', product, 
				:confirm => 'Are you sure?', 
				:method => :delete %>
		</td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>	<%= image_tag @product.photo.url,:width=>"200px" %></p>

<p>
  <b>Title:</b>
  <%= @product.title %>
</p>

<p>
  <b>Description:</b>
  <%= @product.description %>
</p>



<p>
  <b>Price:</b>
  <%= @product.price %>
</p>

<%= button_to 'Add to Cart',line_items_path(:product_id => @product), :remote => true%>