config/routes.rb
EComm::Application.routes.draw do
  
  resources :specialoffers
  get "specialoffers/index"

  resources :specials

  get "pages/home"

  get "pages/contact"

  get 'admin' => "admin#index"

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end

  resources :users

  get "payment_notification/create"

  resources :orders

  resources :line_items

  resources :carts

  get "store/index"

  resources :products
  
  resources :payment_notifications
  

  
  root :to => 'store#index', :as => 'store'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, :dependent => :destroy
  
  def add_product(product_id)
    current_item = line_items.find_by_product_id(product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(:product_id => product_id)
    end
    current_item
  end
  
  def add_special(special_id)
    current_item = line_items.find_by_special_id(special_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(:special_id => special_id)
    end
    current_item
  end
  
  def total_price
    line_items.to_a.sum {|item| item.total_price}
  end
  
  def paypal_url(return_url,notify_url)
      values = {
        :business => 'vimror_1330295712_biz@gmail.com',
        :cmd => '_cart',
        :upload => 1,
        :return => return_url,
        :invoice => id,
        :notify_url => notify_url
      }

      line_items.each_with_index do |item, index|
        values.merge!({
          "amount_#{index + 1}" => item.product.price,
          "item_name_#{index + 1}" => item.product.title,
          "item_number_#{index + 1}" => item.product.id,
          "quantity_#{index + 1}" => item.quantity
        })
      end
      "https://www.sandbox.paypal.com/cgi-bin/webscr?" + values.to_query
    end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :cart
#  belongs_to :special
  
  def total_price
    product.price * quantity
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  
  PAYMENT_TYPES = ["Check","Credit card","Cash"]

  has_many :line_items, :dependent => :destroy
  has_many :transactions, :class_name => "OrderTransaction"
  validates :name, :address1, :email, :presence => true
  #validates :pay_type, :inclusion => PAYMENT_TYPES
  
  before_create :validate_card
  
  attr_accessor :card_number, :card_verification

  def purchase(cart)
    response = GATEWAY.purchase(price_in_cents(cart), credit_card, purchase_options)
    transactions.create!(:action => "purchase",:amont => price_in_cents(cart),:response => response)
    cart.update_attribute(:purchased_at,Time.now) if response.success?
    response.success?
  end
  
  def price_in_cents(cart)
    (cart.total_price*100).round
  end
  
  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end

  private
  
  def purchase_options
    {
      :ip => ip_address,
      :billing_address =>{
        :name => name,
        :address1 => address1,
        :city => city,
        :state => state,
        :country => country,
        :zip => "1001"
      }
    }
  end
  
  def validate_card
    unless credit_card.valid?
      
    end
  end
  
  def credit_card
    @credit_card ||= ActiveMerchant::Billing::CreditCard.new(
    :type => card_type,
    :number => card_number,
    :verification_value => card_verification,
    :month => card_expires_on.month,
    :year => card_expires_on.year,
    :first_name => "first_name",
    :last_name => "last_name"
    )
  end
  
end

app/models/order_transaction.rb
class OrderTransaction < ActiveRecord::Base
  belongs_to :order
  serialize :params
  
  def response=(response)
    self.success        = response.success?
    self.authorization  = response.authorization
    self.message        = response.message
    self.params         = response.params
  rescue ActiveMerchant::ActiveMerchantError => e
    self.success        = false
    self.authorization  = nil
    self.message        = e.message
    self.params         = {}
  end
  
end

app/models/product.rb
class Product < ActiveRecord::Base
  
  has_many :line_items
  before_destroy :ensure_not_referencing_by_any_line_item
  
  validates :title, :description, :presence => true
 # validates :image_url, :allow_blank => true, :format => {:with => %r{\.(gif|jpg|png)$}i,:message => 'must me a URL for GIF,JPG or PNG image.'}
  validates :price, :numericality => {:greater_than_or_equal_to => 0.01 } 
  validates :title, :uniqueness => true 
  
  has_attached_file :photo,
                    :url  => "/assets/products/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/products/:id/:style/:basename.:extension"

  validates_attachment_presence :photo
  validates_attachment_size :photo, :less_than => 5.megabytes
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']
  
   PRODUCT_TYPES = ["Normal","Special"]
 
 private 
 
 #ensure that there is no line items referencing this product.
 
 def ensure_not_referencing_by_any_line_item
   if line_items.empty?
     return true
   else
     errors.add(:base,'Line Items presents')
     return false
   end
 end
end

app/models/special.rb
class Special < ActiveRecord::Base
 # has_many :line_items
  validates :oldprice, :numericality => {:greater_than_or_equal_to => 0.01 } 
  validates :discount, :numericality => {:greater_than_or_equal_to => 0.01 } 
  validates :title, :uniqueness => true 
  
  has_attached_file :photo,
                    :url  => "/assets/products/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/products/:id/:style/:basename.:extension"

  validates_attachment_presence :photo
  validates_attachment_size :photo, :less_than => 5.megabytes
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']
  
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  before_save :encrypt_password
  # validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates :name, :presence => true, :uniqueness=>true
  
   def authenticate(password)
      User.find_by_password_digest(password)
    end
  
  private 
    def ensure_an_admin_remains
      if User.count.zero?
        raise "Can't delete last user"
      end
    end
    
    def encrypt_password
      self.password_digest = password
    end
    
   
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def hidden_div_if(condition,attributes = {}, &block)
    if condition
      attributes["style"] = "display: none"
    end
    content_tag("div",attributes,&block)
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/special1_helper.rb
module Special1Helper
end

app/helpers/specialoffer_helper.rb
module SpecialofferHelper
end

app/helpers/specials_helper.rb
module SpecialsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1>Welcome</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ECommerce Retail Website</title>
  <%= stylesheet_link_tag    "application", :media => "all" %> 
  
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class='<%= controller.controller_name %>'>
	<div>
	    <div id="banner">
		   <div>
		    <%= @page_title || "ECommerce Retail Site"%>
		    </div>
		    <div style="float:right;">
		    <a href="http://www.facebook.com/Macys"><%= image_tag("co_facebookIcon.gif") %></a>
		    </div>
	    </div>
	    <div id="columns">
		    <div id="side">
		    <ul>
			    <li><%= link_to 'Home', store_url %> </li>
			    <li><a href="http://www.google.com">Question</a></li>			
			    <li><%= link_to 'Special',specialoffers_url %> </li>
			    <li><a href="pages/contact">Contact</a></li>
		    </ul>
		
		    <% if session[:user_id] %>
		        <ul>
		            <li><%= link_to 'Orders', order_path %> </li>
		            <li><%= link_to 'Products', products_path %> </li>
		            <li><%= link_to 'Users', users_path %> </li>
		        </ul>
		    <% end %>
		
		    <ul>
		        <!-- AddThis Button BEGIN -->
                <div class="addthis_toolbox addthis_default_style ">
                    <a class="addthis_button_preferred_1"></a>
                    <a class="addthis_button_preferred_2"></a>
                    <a class="addthis_button_preferred_3"></a>
                    <a class="addthis_button_preferred_4"></a>
                    <a class="addthis_button_compact"></a>
                    <a class="addthis_counter addthis_bubble_style"></a>
                </div>
                    <script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4f4feaa25da4fd45"></script>
                <!-- AddThis Button END -->
		    </ul>
		    <ul>
		        
		    </ul>
		</div>
	
		<div id="main">
			<%= yield %>
    	</div>
        
        <div id="rightside">
            <% if @cart %>
			    <%= hidden_div_if(@cart.line_items.empty?,:id=>'cart') do %>
				    <%= render @cart %>
			    <% end %>
		    <% end %>
        </div>
        
  	</div>
  		
  		<div id="footer"> 
    	    All rights reserved by <a href="http://Retailstore.com/">Retailstore.com</a>
    	<div>
    	    
    </div>
    
    
</body>
</html>

app/views/order_notifier/received.text.erb
Dear <%= @order.name %>

Thank you for your recent order from The ECommerce retail store.

You ordered the following items:

<%= render @order.line_items %>

We'll send you a separate e-mail when your order ships.

app/views/order_notifier/shipped.html.erb
<h3>E-commerce Store Shipped</h3>

<p>
    This is just to let you know that we've shipped your recent order:
</p>

<table>
    <tr><th colspan="2">Qty</th><th>Description</th></tr>
    <%= render @order.line_items %>
</table>

app/views/order_notifier/shipped.text.erb
Dear <%= @order.name %>

Thank you for your recent order from The ECommerce retail store.

You ordered the following items:

<%= render @order.line_items %>

We'll send you a separate e-mail when your order ships.